# Project information
site_name: HƯỚNG DẪN SỬ DỤNG
site_url: https://minvoice.vn/
site_author: Nam Phạm
site_description: >-
  Trang web hướng dẫn sử dụng Phần mềm hóa đơn điện tử M-invoice

# Repository
#repo_name: nam1812hy/huongdansudung
#repo_url: https://github.com/nam1812hy

# Copyright
copyright: Copyrights © 2025 Hóa đơn điện tử M-invoice. All Rights Reserved.

# Configuration
theme:
  name: material
  language: vi
  logo: assets/minvoice_white_horizontal.png
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.path
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: custom #indigo
  #     accent: red #indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: custom #indigo
  #     accent: red #indigo
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference
  palette:
    - scheme: default
      primary: custom #indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      default: true # Đặt chế độ sáng làm mặc định

    - scheme: slate
      primary: custom #indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# CSS
extra_css:
  - stylesheets/extra.css

# JS
extra_javascript:
  - stylesheets/extra.js

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  i18n:
    toc: "Mục lục"
    search:
      placeholder: "Search..."
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hoadondientu.m.invoice
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@HoaDonDienTuMinvoice
  generator: false
# Extensions
markdown_extensions:
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - Home: index.md
  - Đơn vị tích hợp:
      - Danh sách đơn vị tích hợp: minvoice2/ds-don-vi-tich-hop/danh-sach-don-vi-tich-hop.md
      - Bổ sung các điểm mới theo NGHỊ ĐỊNH 70/2025/NĐ-CP: minvoice2/ds-don-vi-tich-hop/bo-sung-nd70.md
      - Hướng dẫn tích hợp hóa đơn bán hàng theo Nghị quyết số 174/2024/QH15: minvoice2/ds-don-vi-tich-hop/nqhi-quyet-so-174.md
  - M-invoice 1.0:
      - "":
          - "Hướng dẫn sử dụng":
              - Đăng nhập: minvoice1/huong-dan/dang-nhap.md
              - Dashboard 1.0: minvoice1/huong-dan/dashboard.md
              - Cài đặt plugin: minvoice1/huong-dan/cai-dat-plugin.md
              - Đăng ký / thay đổi tờ khai theo NĐ70: minvoice1/huong-dan/dang-ky-thay-doi-to-khai-theo-ND70.md
              - Thay đổi CKS hoặc thêm CKS mới vào phần mềm theo NĐ70: minvoice1/huong-dan/them-CKS.md
              - Thay đổi địa chỉ doanh nghiệp trên hóa đơn: minvoice1/huong-dan/thay-doi-dia-chi-tren-hoa-don.md
              - Sửa tiền bằng tay: minvoice1/huong-dan/sua-tien-bang-tay.md
              - Tạo hóa đơn bằng file excel: minvoice1/huong-dan/nhap-excel-hang-loat.md
              - Nhập file excel chi tiết: minvoice1/huong-dan/nhap-excel-chi-tiet.md
              - Tải hàng loạt hoá đơn PDF và XML: minvoice1/huong-dan/in-hang-loat.md
              - Thêm mới tài khoản: minvoice1/huong-dan/them-user.md
              - Lấy lại mật khẩu: minvoice1/huong-dan/lay-mat-khau.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - Gửi mail báo "Xác thực không hợp lệ": minvoice1/loi-thuong-gap/gui-mail-loi.md
              - Tổng hợp các lỗi truyền nhận thông điệp CQT: minvoice1/loi-thuong-gap/tong-hop-loi-truyen-nhan-thong-diep-cqt.md
          - "Nghiệp vụ hoá đơn điện tử - Xử lý sai sót":
              #- Hủy hóa đơn: tutorials/nghiep-vu/huy.md
              - Lập biên bản hóa đơn sai sót: minvoice1/xu-ly-sai-sot/lap-bien-ban-hoa-don.md
              - Thay thế hóa đơn: minvoice1/xu-ly-sai-sot/thay-the.md
              - Điều chỉnh hóa đơn: minvoice1/xu-ly-sai-sot/dieu-chinh.md
              - Điều chỉnh hoá đơn về 0 (Tương đương huỷ hoá đơn): minvoice1/xu-ly-sai-sot/dieu-chinh-giam-ve-0.md
              - Thông báo 04/SS-HDDT sai sót theo NĐ70: minvoice1/xu-ly-sai-sot/lap-04ss.md
          - "Danh mục và báo cáo":
              - Báo cáo chi tiết: minvoice1/danh-muc-bao-cao/bao-cao-chi-tiet.md
              - Báo cáo bảng kê bán ra PL01: minvoice1/danh-muc-bao-cao/bao-cao-pl01.md
  - M-invoice 2.0:
      - "":
          - "☰  Tổng quan": minvoice2/tong-quan.md
          - "Hướng dẫn sử dụng":
              - minvoice2/huong-dan/dang-nhap.md
              - minvoice2/huong-dan/dashboard.md
              - minvoice2/huong-dan/chinh-sua-mau-hoa-don.md
              - minvoice2/huong-dan/lap-va-phat-hanh-hoa-don.md
              - minvoice2/huong-dan/plugin.md
              - minvoice2/huong-dan/dang-ky-thay-doi-to-khai-theo-ND70.md
              - minvoice2/huong-dan/them-cks-moi.md
              - minvoice2/huong-dan/cap-nhat-ky-hieu.md
              - minvoice2/huong-dan/thay-doi-dia-chi-tren-hoa-don.md
              - minvoice2/huong-dan/in-hang-loat.md
              - minvoice2/huong-dan/chinh-thap-phan.md
              - minvoice2/huong-dan/gui-mail.md
              - minvoice2/huong-dan/ky-hang-loat.md
              - minvoice2/huong-dan/nhap-excel-hang-loat.md
              - minvoice2/huong-dan/nhap-excel-chi-tiet.md
              - minvoice2/huong-dan/chuyen-ky-hieu.md
              - minvoice2/huong-dan/them-nguoi-dung.md
              - minvoice2/huong-dan/phan-quyen.md
              - minvoice2/huong-dan/keo-bien-nd70.md
              - minvoice2/huong-dan/lay-macqt.md
              - minvoice2/huong-dan/chuyen-doi-so-dinh-danh-ca-nhan-thay-the-ma-so-thue.md
          - "Các câu hỏi và lỗi thường gặp khi sử dụng phần mềm":
              - "Các câu hỏi thường gặp":
                  - minvoice2/cac-cau-hoi-thuong-gap/toi-muon-su-dung-loai-hinh-doanh-nghiep-la-dich-vu-van-chuyen.md
              - "Các lỗi thường gặp":
                  - "Các lỗi ký hoá đơn thường gặp":
                      - minvoice2/cac-loi-thuong-gap/cac-loi-ky-hoa-don-thuong-gap/ban-chua-cai-dat-cong-cu-plugin-de-ky-hoa-don.md
                      - minvoice2/cac-loi-thuong-gap/cac-loi-ky-hoa-don-thuong-gap/ban-da-huy-bo-thao-tac-ky.md
                  - minvoice2/cac-loi-thuong-gap/loi-ket-noi-khong-nhan-duoc-phan-hoi-tu-cqt.md
                  - Hướng dẫn khắc phục các lỗi truyền nhận từ CQT: minvoice2/cac-loi-thuong-gap/tong-hop-loi-truyen-nhan-thong-diep-cqt.md
          - "Nghiệp vụ hoá đơn điện tử - Xử lý sai sót":
              - Lập biên bản hóa đơn sai sót: minvoice2/xu-ly-sai-sot/lap-bien-ban-hoa-don.md
              - minvoice2/xu-ly-sai-sot/dieu-chinh-hoa-don.md
              - Điều chỉnh hoá đơn về 0 (Tương đương hủy hóa đơn): minvoice2/xu-ly-sai-sot/dieu-chinh-giam-ve-0.md
              #    - setup/huy-hoa-don-hang-loat.md
              - minvoice2/xu-ly-sai-sot/thay-the-hoa-don.md
              - minvoice2/xu-ly-sai-sot/dieu-chinh-va-thay-the-tren-he-thong-khac.md
              - minvoice2/xu-ly-sai-sot/giai-trinh-mau04ss.md
          - "Danh mục và báo cáo":
              - minvoice2/danh-muc-bao-cao/bao-cao-tong-hop.md
              - minvoice2/danh-muc-bao-cao/bao-cao-chi-tiet.md
              - minvoice2/danh-muc-bao-cao/danh-muc-hang-hoa.md
              - minvoice2/danh-muc-bao-cao/danh-muc-khach-hang.md
              - minvoice2/danh-muc-bao-cao/danh-muc-don-vi-tinh.md
              - minvoice2/danh-muc-bao-cao/danh-muc-thay-doi-thue-suat.md
          - "Xăng dầu ⛽":
              - minvoice2/xang-dau/huong-dan-xang-dau.md
              - minvoice2/xang-dau/ket-xuat-bao-cao-tru-bom.md
              - minvoice2/xang-dau/cap-nhat-giam-thue-gtgt-xang.md
              - minvoice2/xang-dau/huong-dan-doi-ten-mat-hang-xang-dau.md
  - Chứng từ TNCN:
      - "":
          - "Hướng dẫn sử dụng":
              - Các điểm mới về chứng từ khấu trừ thuế TNCN theo Nghị định 70/2025/NĐ-CP: chung-tu/diem-moi.md
              - Việc cần làm để chuyển đổi đáp ứng Nghị định 70/2025/NĐ-CP: chung-tu/viec-can-lam.md
              - Đăng nhập: chung-tu/dang-nhap.md
              - chung-tu/plugin.md
              - chung-tu/them-cks-moi.md
              - chung-tu/tao-ky-hieu.md
              - chung-tu/lap-va-phat-hanh-chung-tu.md
              - chung-tu/gui-mail.md
              - chung-tu/nhap-excel-hang-loat.md
              - chung-tu/tai-hang-loat.md
              - chung-tu/them-nguoi-dung.md
              - chung-tu/phan-quyen.md
          - "Xử lý sai sót Chứng từ điện tử":
              - chung-tu/thay-the-chung-tu.md
              - chung-tu/dieu-chinh-chung-tu.md
              - chung-tu/giai-trinh-mau04ss.md
          - "Danh mục và báo cáo":
              - chung-tu/danh-muc-khach-hang.md
              - chung-tu/bao-cao-tong-hop.md

  - mSMI:
      - "":
          - Hướng dẫn sử dụng:
              - Đăng nhập: msmi/dang-nhap.md
              - msmi/huong-dan-cai-dat-plugin-msmi.md
              - Dashboard mSMI: msmi/dashboard.md
              - Tra cứu hóa đơn: msmi/tra-cuu-va-tai-hoa-don.md
              - Kiểm tra tình trạng Mã số thuế: msmi/kiem-tra-mst.md
              - Đồng bộ hóa đơn mua vào bán ra: msmi/dong-bo-hoa-don.md
              - msmi/dong-bo-chi-tiet-hoa-don.md
              - Đồng bộ thông báo sai sót 04/SS: msmi/dong-bo-04ss.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - Tài khoản HDDT mất kết nối: msmi/dang-nhap-lai.md
              - Lấy lại mật khẩu trang Hoadondientu: msmi/lay-mat-khau-hddt.md
          - "Danh mục và báo cáo":
              - Bảng kê bán ra - mua vào: msmi/bang-ke.md
              - Báo cáo nhận vào PMKT: msmi/bao-cao-pmkt.md
              - Tờ khai thuế 01GTGT: msmi/to-khai-thue01.md

  - mBHXH:
      - "":
          - Hướng dẫn sử dụng:
              - Đăng nhập: mbhxh/dang-nhap.md
              - mbhxh/dashboard.md
              - mbhxh/dang-ky-tai-khoan.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - ""
          - Nghiệp vụ bảo hiểm xã hội:
              - mbhxh/ho-so-bao-tang.md
              - mbhxh/ho-so-bao-giam.md
              - mbhxh/dieu-chinh-muc-dong.md
              - mbhxh/che-do-om-dau.md
              - mbhxh/che-do-thai-san.md
              - mbhxh/che-do-duong-suc.md
  - mSeller:
      - "":
          - "Hướng dẫn sử dụng trên máy POS 📱":
              - Kết nối phần mềm hoá đơn: mseller/may-pos/ket-noi-phan-mem-hoa-don.md
              - mseller/may-pos/danh-sach-khach-hang.md
              - mseller/may-pos/danh-sach-hang-hoa.md
              - mseller/may-pos/xuat-hoa-don.md
              - mseller/may-pos/huong-dan-in.md
              - mseller/may-pos/sua-xoa-giao-dich.md
              - mseller/may-pos/danh-sach-hoa-don.md
          - "Hướng dẫn sử dụng trên máy tính 💻":
              - mseller/may-tinh/dang-nhap-trang-chu.md
              - mseller/may-tinh/loai-hinh-doanh-nghiep.md
              - mseller/may-tinh/danh-muc-khach-hang.md
              - mseller/may-tinh/danh-muc-hang-hoa.md
              - mseller/may-tinh/quan-ly-don-hang.md
              - mseller/may-tinh/bao-cao-chi-tiet.md
  - Chữ ký số:
      - "":
          - "Chữ ký số IntrustCA":
              - chu-ky-so/chu-ky-so-intrustca/them-cks-intrustca-vao-phan-mem-hoa-don.md
              - chu-ky-so/chu-ky-so-intrustca/thay-doi-cks-intrustca-tren-thue-dien-tu.md
              - chu-ky-so/chu-ky-so-intrustca/huong-dan-ky-so-tren-web-intrustca.md
              - chu-ky-so/chu-ky-so-intrustca/huong-dan-ky-so-tren-app-intrustca.md
          - "Chữ ký số ICA":
              - chu-ky-so/chu-ky-so-ica/cai-dat-ica.md
          - "Ký điện tử":
              - chu-ky-so/ky-dien-tu/huong-dan-ky-so-tren-file-pdf-foxit-reader.md
  - Tài liệu:
      - "":
          - "Tài liệu kỹ thuật 🖥️":
              - tai-lieu/huong-dan-dinh-danh-to-chuc.md
          - "Tài liệu kinh doanh 💼":
              - tai-lieu/tai-lieu-kinh-doanh.md
          - "New-invoice":
              - tai-lieu/new-invoice/dang-ky-thay-doi-to-khai-theo-ND70.md
              - tai-lieu/new-invoice/thay-doi-dia-chi-tren-hoa-don.md
              - tai-lieu/new-invoice/chuyen-doi-minvoice.md
