# Project information
site_name: HƯỚNG DẪN SỬ DỤNG
site_url: https://minvoice.vn/
site_author: Nam Phạm
site_description: >-
  Trang web hướng dẫn sử dụng Phần mềm hóa đơn điện tử M-invoice

# Repository
#repo_name: nam1812hy/huongdansudung
#repo_url: https://github.com/nam1812hy

# Copyright
copyright: Copyrights © 2025 Hóa đơn điện tử M-invoice. All Rights Reserved.

# Configuration
theme:
  name: material
  language: vi
  logo: assets/minvoice_white_horizontal.png
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.path
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: custom #indigo
  #     accent: red #indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: custom #indigo
  #     accent: red #indigo
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference
  palette:
    - scheme: default
      primary: custom #indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      default: true # Đặt chế độ sáng làm mặc định

    - scheme: slate
      primary: custom #indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# CSS
extra_css:
  - stylesheets/extra.css

# JS
extra_javascript:
  - stylesheets/extra.js

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  i18n:
    toc: "Mục lục"
    search:
      placeholder: "Search..."
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hoadondientu.m.invoice
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@HoaDonDienTuMinvoice
  generator: false
# Extensions
markdown_extensions:
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  # - Home: index.md
  # - Getting started:
  #     - Installation: getting-started.md
  #     - Creating your site: creating-your-site.md
  #     - Publishing your site: publishing-your-site.md
  #     - Customization: customization.md
  #     - Conventions: conventions.md
  #     - Browser support: browser-support.md
  #     - Enterprise feedback: enterprise-support.md
  #     - Philosophy: philosophy.md
  #     - Alternatives: alternatives.md
  #     - License: license.md
  #     - Tutorials:
  #         - tutorials/index.md
  #         - "Blogs":
  #             - tutorials/blogs/basic.md
  #             - tutorials/blogs/navigation.md
  #             - tutorials/blogs/engage.md
  #         - "Social cards":
  #             - tutorials/social/basic.md
  #             - tutorials/social/custom.md
  #     - Changelog:
  #         - changelog/index.md
  #         - How to upgrade: upgrade.md
  # - Setup:
  #     - setup/index.md
  #     - Changing the colors: setup/changing-the-colors.md
  #     - Changing the fonts: setup/changing-the-fonts.md
  #     - Changing the language: setup/changing-the-language.md
  #     - Changing the logo and icons: setup/changing-the-logo-and-icons.md
  #     - Ensuring data privacy: setup/ensuring-data-privacy.md
  #     - Setting up navigation: setup/setting-up-navigation.md
  #     - Setting up site search: setup/setting-up-site-search.md
  #     - Setting up site analytics: setup/setting-up-site-analytics.md
  #     - Setting up social cards: setup/setting-up-social-cards.md
  #     - Setting up a blog: setup/setting-up-a-blog.md
  #     - Setting up tags: setup/setting-up-tags.md
  #     - Setting up versioning: setup/setting-up-versioning.md
  #     - Setting up the header: setup/setting-up-the-header.md
  #     - Setting up the footer: setup/setting-up-the-footer.md
  #     - Adding a git repository: setup/adding-a-git-repository.md
  #     - Adding a comment system: setup/adding-a-comment-system.md
  #     - Building an optimized site: setup/building-an-optimized-site.md
  #     - Building for offline usage: setup/building-for-offline-usage.md
  #     - Extensions:
  #         - setup/extensions/index.md
  #         - Python Markdown: setup/extensions/python-markdown.md
  #         - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  # - Plugins:
  #     - plugins/index.md
  #     - Blog: plugins/blog.md
  #     - Group: plugins/group.md
  #     - Info: plugins/info.md
  #     - Meta: plugins/meta.md
  #     - Offline: plugins/offline.md
  #     - Optimize: plugins/optimize.md
  #     - Privacy: plugins/privacy.md
  #     - Projects: plugins/projects.md
  #     - Search: plugins/search.md
  #     - Social: plugins/social.md
  #     - Tags: plugins/tags.md
  #     - Typeset: plugins/typeset.md
  #     - Requirements:
  #         - Image processing: plugins/requirements/image-processing.md
  #         - Caching: plugins/requirements/caching.md
  # - Reference:
  #     - reference/index.md
  #     - Admonitions: reference/admonitions.md
  #     - Annotations: reference/annotations.md
  #     - Buttons: reference/buttons.md
  #     - Code blocks: reference/code-blocks.md
  #     - Content tabs: reference/content-tabs.md
  #     - Data tables: reference/data-tables.md
  #     - Diagrams: reference/diagrams.md
  #     - Footnotes: reference/footnotes.md
  #     - Formatting: reference/formatting.md
  #     - Grids: reference/grids.md
  #     - Icons, Emojis: reference/icons-emojis.md
  #     - Images: reference/images.md
  #     - Lists: reference/lists.md
  #     - Math: reference/math.md
  #     - Tooltips: reference/tooltips.md
  # - Insiders:
  #     - insiders/index.md
  #     - Why sponsor us: insiders/why-sponsor-us.md
  #     - What's in it for you: insiders/benefits.md
  #     - Who is sponsoring: insiders/our-sponsors.md
  #     - Sponsoring tiers: insiders/sponsoring-tiers.md
  #     - How to sponsor: insiders/how-to-sponsor.md
  #     - Additional information:
  #         - Payment and billing: insiders/payment-and-billing.md
  #         - Access management: insiders/access-management.md
  #         - Runtime and cancellation: insiders/runtime-and-cancellation.md
  #         - Privacy: insiders/privacy.md
  #         - License: insiders/license.md
  #         - Support: support.md
  #     - Using Insiders:
  #         - Getting started: insiders/getting-started.md
  #     - Changelog:
  #         - insiders/changelog/index.md
  #         - How to upgrade: insiders/upgrade.md
  # - Community:
  - Home: index.md
  # - Danh sách đơn vị tích hợp:
  #     - "":
  #         - "":
  #             - Danh sách đơn vị tích hợp: setup/ds-don-vi-tich-hop/danh-sach-don-vi-tich-hop.md
  - Đơn vị tích hợp:
      - Danh sách đơn vị tích hợp: setup/ds-don-vi-tich-hop/danh-sach-don-vi-tich-hop.md
      - Bổ sung các điểm mới theo NGHỊ ĐỊNH 70/2025/NĐ-CP: setup/ds-don-vi-tich-hop/bo-sung-nd70.md
      - Hướng dẫn tích hợp hóa đơn bán hàng theo Nghị quyết số 174/2024/QH15: setup/ds-don-vi-tich-hop/nqhi-quyet-so-174.md
  - M-invoice 1.0:
      # - Installation: getting-started.md
      # - Publishing your site: publishing-your-site.md
      # - Customization: customization.md
      # - Conventions: conventions.md
      # - Browser support: browser-support.md
      # - Enterprise feedback: enterprise-support.md
      # - Philosophy: philosophy.md
      # - Alternatives: alternatives.md
      # - License: license.md
      - "":
          - "Hướng dẫn sử dụng":
              - Đăng nhập: tutorials/thao-tac/dang-nhap.md
              - Dashboard 1.0: tutorials/thao-tac/dashboard.md
              - Thêm mới chữ ký số: tutorials/thao-tac/them-CKS.md
              - Cài đặt plugin: tutorials/thao-tac/cai-dat-plugin.md
              - Thay đổi địa chỉ: tutorials/thao-tac/thay-doi-dia-chi.md
              - Sửa tiền bằng tay: tutorials/thao-tac/sua-tien-bang-tay.md
              - Tạo hóa đơn bằng file excel: tutorials/thao-tac/nhap-excel-hang-loat.md
              - Nhập file excel chi tiết: tutorials/thao-tac/nhap-excel-chi-tiet.md
              - Tải hàng loạt hoá đơn PDF và XML: tutorials/thao-tac/in-hang-loat.md
              - Thêm mới tài khoản: tutorials/thao-tac/them-user.md
              - Lấy lại mật khẩu: tutorials/thao-tac/lay-mat-khau.md
              - Báo cáo chi tiết: tutorials/thao-tac/bao-cao-chi-tiet.md
              - Báo cáo bảng kê bán ra PL01: tutorials/thao-tac/bao-cao-pl01.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - Gửi mail báo "Xác thực không hợp lệ": tutorials/loi-thuong-gap/gui-mail-loi.md
          - "Nghiệp vụ hoá đơn điện tử":
              #- Hủy hóa đơn: tutorials/nghiep-vu/huy.md
              - Lập biên bản hóa đơn sai sót: tutorials/nghiep-vu/lap-bien-ban-hoa-don.md
              - Điều chỉnh hóa đơn: tutorials/nghiep-vu/dieu-chinh.md
              - Điều chỉnh hoá đơn về 0: tutorials/nghiep-vu/dieu-chinh-giam-ve-0.md
              - Thay thế hóa đơn: tutorials/nghiep-vu/thay-the.md
              - Giải trình hóa đơn: tutorials/nghiep-vu/lap-04ss.md
              - Gửi mẫu 04ss thay thế hoặc điều chỉnh hoá đơn: tutorials/nghiep-vu/thay-the-mau04ss.md
  - M-invoice 2.0:
      - "":
          - "Hướng dẫn sử dụng":
              - setup/dang-nhap.md
              - setup/dashboard.md
              - setup/lap-va-phat-hanh-hoa-don.md
              - setup/sao-chep-hoa-don.md
              - setup/plugin.md
              - setup/them-cks-moi.md
              - setup/cap-nhat-ky-hieu.md
              - setup/thay-doi-thong-tin-doanh-nghiep.md
              - setup/in-hang-loat.md
              - setup/chinh-thap-phan.md
              - setup/gui-mail.md
              - setup/ky-hang-loat.md
              - setup/nhap-excel-hang-loat.md
              - setup/nhap-excel-chi-tiet.md
              - setup/chuyen-ky-hieu.md
              - setup/them-nguoi-dung.md
              - setup/phan-quyen.md
              - setup/keo-bien-nd70.md
              - setup/lay-macqt.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - setup/cac-loi-ky-hoa-don.md
              - setup/tong-hop-cac-loi-cqt.md
          - "Nghiệp vụ hoá đơn điện tử":
              - setup/thay-the-hoa-don.md
              - setup/dieu-chinh-hoa-don.md
              - Điều chỉnh hoá đơn về 0: setup/dieu-chinh-giam-ve-0.md
              - setup/dieu-chinh-va-thay-the-tren-he-thong-khac.md
              - Lập biên bản hóa đơn sai sót: setup/lap-bien-ban-hoa-don.md
              #    - setup/huy-hoa-don-hang-loat.md
              - setup/giai-trinh-mau04ss.md
              - setup/thay-the-mau04ss.md
          - "Danh mục và báo cáo":
              - setup/bao-cao-tong-hop.md
              - setup/bao-cao-chi-tiet.md
              - setup/danh-muc-hang-hoa.md
              - setup/danh-muc-khach-hang.md
              - setup/danh-muc-don-vi-tinh.md
              - setup/danh-muc-thay-doi-thue-suat.md
          - "Xăng dầu ⛽":
              - setup/xang-dau/huong-dan-xang-dau.md
              - setup/xang-dau/ket-xuat-bao-cao-tru-bom.md
  - Chứng từ TNCN:
      - "":
          - "Hướng dẫn sử dụng":
              - Các điểm mới về chứng từ khấu trừ thuế TNCN theo Nghị định 70/2025/NĐ-CP: chung-tu/diem-moi.md
              - Đăng nhập: chung-tu/dang-nhap.md
              - chung-tu/plugin.md
              - chung-tu/them-cks-moi.md
              - chung-tu/tao-ky-hieu.md
              - chung-tu/lap-va-phat-hanh-chung-tu.md
              - chung-tu/gui-mail.md
              - chung-tu/nhap-excel-hang-loat.md
              - chung-tu/tai-hang-loat.md
              - chung-tu/them-nguoi-dung.md
              - chung-tu/phan-quyen.md
          - "Nghiệp vụ chứng từ điện tử":
              - chung-tu/thay-the-chung-tu.md
              - chung-tu/dieu-chinh-chung-tu.md
              - chung-tu/giai-trinh-mau04ss.md
          - "Danh mục và báo cáo":
              - chung-tu/danh-muc-khach-hang.md
              - chung-tu/bao-cao-tong-hop.md

  - mSMI:
      - "":
          - Hướng dẫn sử dụng:
              - Đăng nhập: tutorials/mSMI/dang-nhap.md
              - Dashboard mSMI: tutorials/mSMI/dashboard.md
              - Tra cứu hóa đơn: tutorials/mSMI/tra-cuu-va-tai-hoa-don.md
              - Kiểm tra tình trạng Mã số thuế: tutorials/mSMI/kiem-tra-mst.md
              - Đồng bộ hóa đơn mua vào bán ra: tutorials/mSMI/dong-bo-hoa-don.md
              - Đồng bộ thông báo sai sót 04/SS: tutorials/mSMI/dong-bo-04ss.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - Tài khoản HDDT mất kết nối: tutorials/mSMI/dang-nhap-lai.md
              - Lấy lại mật khẩu trang Hoadondientu: tutorials/mSMI/lay-mat-khau-hddt.md
          - "Danh mục và báo cáo":
              - Bảng kê bán ra - mua vào: tutorials/mSMI/bang-ke.md
              - Báo cáo nhận vào PMKT: tutorials/mSMI/bao-cao-pmkt.md
              - Tờ khai thuế 01GTGT: tutorials/mSMI/to-khai-thue01.md
          # - "Các thao tác thường gặp khi sử dụng phần mềm":
          #     - setup/plugin.md
          #     - setup/them-cks-moi.md
          #     - setup/lap-va-phat-hanh-hoa-don.md
          #     - setup/thay-doi-thong-tin-doanh-nghiep.md
          #     - setup/xoa-hoa-don.md
          #     - setup/sua-hoa-don.md
          #     - setup/in-hang-loat.md
          #     - setup/chinh-thap-phan.md
          #     - setup/sao-chep-hoa-don.md
          #     - setup/gui-mail.md
          #     - setup/ky-hang-loat.md
          #     - setup/chuyen-ky-hieu.md
          #     - setup/cap-nhat-ky-hieu.md
          #       # - tutorials/thaoTac/suaTienBangTay.md
          #       # - tutorials/thaoTac/baoCaoChiTietHoaDon.md
          #       # - tutorials/thaoTac/basic.md
          #       # - tutorials/thaoTac/navigation.md
          #       # - tutorials/thaoTac/engage.md
          # - "Nghiệp vụ hoá đơn điện tử":
          #     - setup/thay-the-hoa-don.md
          #     - setup/dieu-chinh-hoa-don.md
          #     - setup/dieu-chinh-va-thay-the-tren-he-thong-khac.md
          #     - setup/huy-hoa-don.md
          #     - setup/huy-hoa-don-hang-loat.md
          #       #- setup/setting-up-versioning.md
          #       # - "Điều chỉnh hoá đơn":
          #       #     - setup/dieuChinh.md
          #       # # - tutorials/social/basic.md
          #       # # - tutorials/social/custom.md
          # - "Danh mục và báo cáo":
          #     - setup/bao-cao-tong-hop.md
          #     - setup/bao-cao-chi-tiet.md
          #     - setup/danh-muc-hang-hoa.md
          #     - setup/danh-muc-khach-hang.md
          #     - setup/danh-muc-don-vi-tinh.md
          #     - setup/danh-muc-thay-doi-thue-suat.md
          # - "Người dùng và phân quyền":
          #     - setup/them-nguoi-dung.md
          #     - setup/phan-quyen.md
  - mBHXH:
      - "":
          - Hướng dẫn sử dụng:
              - Đăng nhập: tutorials/mBHXH/dang-nhap.md
              - tutorials/mBHXH/dashboard.md
              - tutorials/mBHXH/dang-ky-tai-khoan.md
          - "Các lỗi thường gặp khi sử dụng phần mềm":
              - ""
          - Nghiệp vụ bảo hiểm xã hội:
              - tutorials/mBHXH/ho-so-bao-tang.md
              - tutorials/mBHXH/ho-so-bao-giam.md
              - tutorials/mBHXH/dieu-chinh-muc-dong.md
              - tutorials/mBHXH/che-do-om-dau.md
              - tutorials/mBHXH/che-do-thai-san.md
              - tutorials/mBHXH/che-do-duong-suc.md
  - mSeller:
      - "":
          - "Hướng dẫn sử dụng trên máy POS 📱":
              - Kết nối phần mềm hoá đơn: setup/ban-hang/ket-noi-phan-mem-hoa-don.md
              - setup/ban-hang/danh-sach-khach-hang.md
              - setup/ban-hang/danh-sach-hang-hoa.md
              - setup/ban-hang/xuat-hoa-don.md
              - setup/ban-hang/sua-xoa-giao-dich.md
              - setup/ban-hang/danh-sach-hoa-don.md
          - "Hướng dẫn sử dụng trên máy tính 💻":
              - setup/ban-hang/may-tinh/dang-nhap-trang-chu.md
              - setup/ban-hang/may-tinh/danh-muc-khach-hang.md
              - setup/ban-hang/may-tinh/danh-muc-hang-hoa.md
              - setup/ban-hang/may-tinh/quan-ly-don-hang.md
              - setup/ban-hang/may-tinh/bao-cao-chi-tiet.md
  - Chữ ký số:
      - "":
          - "Chữ ký số IntrustCA":
              - setup/Chu-ky-so/them-intrustca.md
              - setup/Chu-ky-so/thue-dien-tu-intrustca.md
              - setup/Chu-ky-so/web-intrustca.md
              - setup/Chu-ky-so/app-intrustca.md
          - "Chữ ký số ICA":
              - setup/Chu-ky-so/cai-dat-ica.md
          - "Ký điện tử":
              - setup/Chu-ky-so/ky-bang-foxit.md
  - Tài liệu:
      - "":
          - "Tài liệu kinh doanh 💼":
              - setup/tai-lieu/tai-lieu-kinh-doanh.md
          - "Tài liệu kỹ thuật 🖥️":
              - ""
